APONCoreWebsite/Pages/Admin/AddCast.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages.Admin
{
    public class AddCastModel : ViewModelBase
    {
        public AddCastModel(IAuthService authService, IMetaTagService imts, IDataService ds) : base(authService, imts, ds)
        {

        }

        public void OnGet()
        {

        }
    }
}

APONCoreWebsite/Pages/Admin/AddComic.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using APONCoreLibrary.Models;
using APONCoreWebsite.Pages.Shared;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using System.Net.Http;

namespace APONCoreWebsite.Pages.Admin
{
    public class AddComicModel : ViewModelBase
    {
        public ITagService tagService { get; set; }

        public string ResponseMessage { get; set; }
        public bool EditorLoggedIn { get; set; }
        public ComicStrip CS { get; set; }

        public int SavedStripID { get; set; }
        bool Saved { get; set; }

        public AddComicModel(IAuthService authService, IMetaTagService imts, ITagService ts, IDataService ds) : base(authService, imts, ds)
        {
            this.tagService = ts;

        }

        public async Task<IActionResult> OnGet()
        {
            string response = await DS.GetAsync("user/IsEditorLoggedIn");
            EditorLoggedIn = Newtonsoft.Json.JsonConvert.DeserializeObject<bool>(response);
            SavedStripID = -1;
            return Page();
        }

        public async Task<IActionResult> OnPostComicAsync()
        {
            string response = await DS.GetAsync("user/IsEditorLoggedIn");
            EditorLoggedIn = Newtonsoft.Json.JsonConvert.DeserializeObject<bool>(response);

            if (EditorLoggedIn)
            {
                ComicStrip CS = new ComicStrip();
                CS.DefaultHeight = int.Parse(Request.Form["DefaultHeight"]);
                CS.DefaultWidth = int.Parse(Request.Form["DefaultWidth"]);
                CS.Description = Request.Form["Description"];
                CS.Name = Request.Form["Name"];
                CS.Enabled = (int.Parse(Request.Form["enabledStatus"]) != 0);
                CS.ImageURL = Request.Form["imgURLtextbox"];

                HttpResponseMessage message = await DS.PostAsync(CS, "comic/AddComic");
                if (message.StatusCode != System.Net.HttpStatusCode.OK)
                {
                    ResponseMessage = "There was a problem uploading the comic.";
                }
                else
                {
                    string newEpID = await DS.GetAsync("comic/GetLatestComicID");
                    SavedStripID = Newtonsoft.Json.JsonConvert.DeserializeObject<int>(newEpID);

                }
            }

            return Page();
        }
    }
}

APONCoreWebsite/Pages/Admin/AddEpisode.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Helpers;
using APONCoreLibrary.Models;
using APONCoreWebsite.Pages.Shared;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages
{
    [DisableRequestSizeLimit]
    public class AddEpisodeModel : ViewModelBase
    {

        [BindProperty]
        public string EpisodeSaved { get; set; }

        [BindProperty]
        public bool AttemptedSave { get; set; }


        public ITagService tagService { get; set; }

   

        public _tagConsoleModel TCM { get; set; }

        [BindProperty(SupportsGet = true)]
        public int SeriesID { get; set; }

        public APONCoreLibrary.Models.Series EpSeries { get; set; }

        public EpisodeWithTags Episode { get; set; }

        public int SavedEpisodeID { get; set; }

        public bool Affiliate { get; set; }

        public bool PageNotFound { get; set; }

        [BindProperty]
        public IFormFile UploadFile { get; set; }

        public string ResponseMessage { get; set; }

        ISeriesService SS { get; set; }
        public AddEpisodeModel(IAuthService authService,  IMetaTagService imts, ITagService ts, IDataService ds, ISeriesService ss) : base(authService, imts, ds)
        {
            this.tagService = ts;
            SavedEpisodeID = -1;

              Episode = new EpisodeWithTags();
            Episode.episode = new Episode();
            SS = ss;
        }


        public async Task<IActionResult> OnGetAsync()
        {
            AttemptedSave = false;
            EpisodeSaved = "False";
            if (int.Parse(myAuthService.getUser().AuthLevel) < 4)
            {

                TCM = new _tagConsoleModel(tagService)
                {
                    Tags = await tagService.GetTags(false)
                };

                string Response = await DS.GetAsync("Series/" + SeriesID);

                if (Response.ToLower().Contains("could not find"))
                {
                    PageNotFound = true;
                    return Page();
                }

                EpSeries = Newtonsoft.Json.JsonConvert.DeserializeObject<APONCoreLibrary.Models.Series>(Response);

                int dayOfTheWeek = (int)DateTime.Now.DayOfWeek;
                DateTime D;

                if (EpSeries.ShowDate > dayOfTheWeek)
                {
                    D = DateTime.Now.AddDays(EpSeries.ShowDate - dayOfTheWeek);
                }
                else if (EpSeries.ShowDate < dayOfTheWeek)
                {
                    D = DateTime.Now.AddDays((EpSeries.ShowDate + 7) - dayOfTheWeek);
                }
                else
                {
                    D = DateTime.Now;
                    
                }
              
                Episode.episode.ShowDate = new DateTime(D.Year, D.Month, D.Day, EpSeries.DefaultHour - 2, 0, 0);
                Episode.episode.EpImageURL = EpSeries.ImageURL;
                Episode.episode.SplashImageURL = EpSeries.SplashImageURL;
                Episode.episode.Keywords = EpSeries.Keywords;
            }
            return Page();
        }



    
        
        public async Task<IActionResult> OnPostEpisodeAsync()
        {
            bool epIsAffiliate = false;
            if (!string.IsNullOrEmpty(Request.Form["affiliateChckbx"]) && Request.Form["affiliateChckbx"] == "on")
            {
                epIsAffiliate = true;
            }
            
            if (!epIsAffiliate)
            {
                string s = UploadFile.Name;
                AttemptedSave = true;
                EpisodeSaved = "False";
                HttpResponseMessage UploadResponse = await DS.PostImageAsync(UploadFile, "Episodes/ULE/" + SeriesID);
                if (UploadResponse.StatusCode != System.Net.HttpStatusCode.OK)
                {
                    ResponseMessage = "Error Uploading file: " + UploadResponse.StatusCode.ToString();
                    AttemptedSave = true;
                    return Page();
                }
            }
            Episode = new EpisodeWithTags();
          
            List<Tag> Tags = new List<Tag>();

            Episode E = new Episode();

            if (epIsAffiliate)
            {
                E.Local = false;
                E.FileURL = Request.Form["affiliateFileURL"];
                E.NonLocalType = 1;
            }
            else
            {
                E.FileURL = UploadFile.FileName;
                E.Local = true;
                E.NonLocalType = 3;
            }
     
            E.Description = Request.Form["shortDescription"];
            E.EpImageURL = Request.Form["imgURLtextbox"];
            E.Keywords = Request.Form["keywords"];
            E.PostedByUserID = myAuthService.getUserID();
            E.SeriesID = SeriesID;
            E.ShowDate = DateTime.Parse(Request.Form["myDatePicker"]);
            E.Size = Request.Form["epSize"];
            E.SplashImageURL = Request.Form["splashImageInput"];
            E.Time = Request.Form["epTime"];
            E.Title = Request.Form["episodeTitle"];
            E.TrackNumber = int.Parse(Request.Form["trackNumber"]);
            E.WebDescription = Request.Form["tinymcetextarea"];

           
          

            string TagList = Request.Form["selectedTagIDs"];
            if (TagList.Length > 0)
            {
                if (TagList.Substring(0, 1) == ",")
                {
                    TagList = TagList.Substring(1, TagList.Length - 1);
                }
                string splitter = ",";
                string[] taglistarray = TagList.Split(splitter);

                for (int i = 0; i < taglistarray.Length; i++)
                {

                    if (taglistarray[i] != "")
                    {
                        int TID = -1;
                        if (int.TryParse(taglistarray[i], out TID))
                        {
                            Tag t = new Tag();
                            t.TagID = TID;
                            Tags.Add(t);
                        }

                        //Tag t = new Tag();
                        //t.TagID = int.Parse(taglistarray[i]);
                        //Tags.Add(t);
                    }
                }
            }

            Episode.episode = E;
            Episode.tags = Tags;

            HttpResponseMessage message = await DS.PostAsync(Episode, "Episodes/AddEpisode");

            if (message.StatusCode != System.Net.HttpStatusCode.OK)
            {
                ResponseMessage = "There was a problem uploading the episode.";
            }
            else
            {
                string newEpID = await DS.GetAsync("Episodes/GetLatestEpisodeID");
                SavedEpisodeID = Newtonsoft.Json.JsonConvert.DeserializeObject<int>(newEpID);

            }
            //Populate to restore page

         
            AttemptedSave = true;
            EpisodeSaved = "True";
            EpSeries = await SS.GetSeriesByID(SeriesID);

        
            return Page();
        }

     
    }
}

APONCoreWebsite/Pages/Admin/AddFeature.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Http;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using APONCoreLibrary.Models;
using APONCoreWebsite.Pages.Shared;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages.Admin
{
    public class AddFeatureModel : ViewModelBase
    {

        public AddFeatureModel(IAuthService authService,  IMetaTagService imts, ITagService ts, IDataService ds) : base(authService, imts, ds)
        {
            this.tagService = ts;
         
        }

        [BindProperty]
        public bool FeatureSaved { get; set; }

        [BindProperty]
        public bool AttemptedSave { get; set; }

  
        public ITagService tagService { get; set; }


        public int CurUserID { get; set; }
        public List<User> Editors { get; set; }

        public _tagConsoleModel TCM { get; set; }

        [BindProperty(SupportsGet = true)]
        public int FeatureID { get; set; }

        public NewsWithTags Feature { get; set; }

        public bool PageNotFound { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            AttemptedSave = false;
            TCM = new _tagConsoleModel(tagService);
            TCM.Tags = await tagService.GetTags(false);

            CurUserID = myAuthService.getUserID();
            if (int.Parse(myAuthService.getUser().AuthLevel) < 4)
            {
                if (FeatureID == 0)
                {
                    Feature = new NewsWithTags();
                    Feature.News = new News();
                    Feature.tags = new List<Tag>();
                    Feature.News.PostDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day);
                    Feature.News.AuthorID = CurUserID;
                }
                else
                {
                    string result = await DS.GetAsync("news/GetNewsItemWTags/" + FeatureID);

                    if (result.ToLower().Contains("page not found"))
                    {
                        PageNotFound = true;
                        return Page();
                    }
                    Feature = Newtonsoft.Json.JsonConvert.DeserializeObject<NewsWithTags>(result);

                    ProcessTagsForTCM();
                }
                //Otherwise Get the feature to be populated in the form.

             
                string EditorsResult = await DS.GetAsync("crewmembers/geteditors");
                Editors = Newtonsoft.Json.JsonConvert.DeserializeObject<List<User>>(EditorsResult);

                if (FeatureID == 0)
                {
                    return Page();
                }

            }

            return Page();
        }


        private void ProcessTagsForTCM()
        {

            string tags = "";
            string indicies = "";
            for (int i = 0; i < Feature.tags.Count; i++)
            {

                int index = TCM.Tags.FindIndex(a => a.TagID == Feature.tags[i].TagID);

                if (!string.IsNullOrEmpty(TCM.Tags[index].Name))
                {
                    if (i == 0)
                    {
                        tags = Feature.tags[i].TagID.ToString();
                        if (index != -1)
                        {
                            indicies = index.ToString();
                        }

                    }
                    else
                    {
                        tags += "," + Feature.tags[i].TagID.ToString();
                        if (index != -1)
                        {
                            indicies += "," + index.ToString();
                        }
                    }
                }

            }

            TCM.SelectedIDs = tags;
            TCM.SelectedIndicies = indicies;
        }

        public async Task<IActionResult> OnPostFeatureAsync()
        {
            AttemptedSave = true;

            Feature = new NewsWithTags();
            Feature.tags = new List<Tag>();
            Feature.News = new News();


            Feature.News.Headline = Request.Form["headline"];
            Feature.News.LongText = Request.Form["tinymcetextarea"];
            Feature.News.Text = Request.Form["shortDescription"];
            Feature.News.PostDate = DateTime.Parse(Request.Form["myDatePicker"]);
            Feature.News.TempTweet = "";  //Removed and filled with nothing.
            Feature.News.ImageURL = Request.Form["smallImageInput"];
            Feature.News.SplashImageURL = Request.Form["splashImageInput"];

            if (myAuthService.getUserAuthLevel() > 2)
            {
                Feature.News.AuthorID = myAuthService.getUserID();
            }
        else
            {
                Feature.News.AuthorID = int.Parse(Request.Form["editor"]);
            }
            //If the ID is 0, add them.
            Feature.News.Status = 4;


            //AddTags
            string Tags = Request.Form["selectedTagIDs"];
            if (Tags.Length > 0)
            {
                if (Tags.Substring(0, 1) == ",")
                {
                    Tags = Tags.Substring(1, Tags.Length - 1);
                }
                string splitter = ",";
                string[] taglist = Tags.Split(splitter);

                for (int i = 0; i < taglist.Length; i++)
                {
                   
                    if (taglist[i] != "")
                    {
                        Tag t = new Tag();
                        t.TagID = int.Parse(taglist[i]);
                        Feature.tags.Add(t);
                    }
                }
            }
            CurUserID = myAuthService.getUserID();

            string EditorsResult = await DS.GetAsync("crewmembers/geteditors");
            Editors = Newtonsoft.Json.JsonConvert.DeserializeObject<List<User>>(EditorsResult);
            HttpResponseMessage Response;

            if (FeatureID == 0)
            {
                Response = await DS.PostAsync(Feature, "news/addnews");
            }
            else
            {
                Feature.News.NewsID = FeatureID;
                Response = await DS.PutAsync(Feature, "news/UpdateNews");
            }

            if (Response.Content.ToString().ToLower().Contains("found"))
            {
                FeatureSaved = false;

            }
            else
            {
                AttemptedSave = true;
                FeatureSaved = true;
            }


            TCM = new _tagConsoleModel(tagService);
            TCM.Tags = await tagService.GetTags(false);
            ProcessTagsForTCM();
            //IF the ID is not 0, update them
            FeatureSaved = true;
            return Page();
        }


    }
}

APONCoreWebsite/Pages/Admin/AddSeriesCast.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages.Admin
{
    public class AddSeriesCastModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

APONCoreWebsite/Pages/Admin/AddCast.cshtml
@page "/Admin/AddCast"
@model APONCoreWebsite.Pages.Admin.AddCastModel
@{
    ViewData["Title"] = "AddCast";
}

<h1>AddCast</h1>


@{ 

    if (Model.UserAuthLevel < 3)
    {

        APONCoreLibrary.Models.Cast C = new APONCoreLibrary.Models.Cast();
       
        <form id="frmCast">
            <div>
                <label for="firstName">First Name</label>
                <input type="text" id="firstName" name="firstName" />
            </div>


        </form>
    }
}


@section Scripts
{
<script type="text/javascript">

   
    $(document).ready(function () {

        CheckIfAdmin();
    }
</script>
}

APONCoreWebsite/Pages/Admin/AddComic.cshtml
@page  "/Admin/AddComic/"
@model APONCoreWebsite.Pages.Admin.AddComicModel
@{

    if (Model.EditorLoggedIn)
    { 

    <form method="post" asp-page-handler="Comic" id="mainForm" enctype="multipart/form-data">
        <div class="grid-row">
            <div class="col-1-of-2" style="border-right: solid 1px">
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                           class="form-control w100"
                           id="Name"
                           required
                           name="Name" />
                </div>
                <div class="form-group">
                    <label for="title">Description</label>
                    <input type="text"
                           class="form-control w100"
                           id="description"
                           required
                           name="description" />
                </div>
                <div class="form-group">
                    <label for="title">Default Width</label>
                    <input type="text"
                           class="form-control w100"
                           id="DefaultWidth"
                           required
                           name="DefaultWidth" />
                </div>
                <div class="form-group">
                    <label for="title">Default Height</label>
                    <input type="text"
                           class="form-control w100"
                           id="DefaultHeight"
                           required
                           name="DefaultHeight" />
                </div>
                <div class="form-group">
                    <label for="title">Status</label>
                    <select name="enabledStatus" id="enabledStatus">
                        <option value="0">Disabled</option>
                        <option value="1">Enabled</option>

                    </select>
                </div>
                <label class="mt-2" for="imageURL">Image Location</label>
                <input type="text"
                       class="form-control"
                       id="imgURLtextbox"
                       required
                       name="imgURLtextbox"
                       oninput="updateImg('imgURLtextbox', 'imgMainImage')" />

                <input type="file"
                       id="imgFileInput"
                       name="imgFileInput"
                       accept=".png,.jpg"
                       #imgURLInput
                       onchange="startImageSubmit(event, 'imgFileInput', 'imgURLtextbox', 'imgMainImage');" />
                <br />
                <img id="imgMainImage"
                     name="imgMainImage"
                     class="editorImage" />

            </div>
            <div class="col-1-of-2">


                <button id="btnAddComicSubmit"
                        type="submit"
                        class="btn btn-success"
                       >
                    Submit
                </button>
            </div>
        </div>

    </form>
    }
}
@section Scripts
{
    <script type="text/javascript">

          $(document).ready(function () {

            let LoggedIn = "@Model.EditorLoggedIn";
            
            if (LoggedIn == "False") {
             
                logoutFromSession();
              }

              if (@Model.SavedStripID != -1) {
                  window.location.href = "../ComicStrips";
              }

         });

        function startImageSubmit(evt, senderObj, txtUpdateField, imgUpdateField) {
            let fd = new FormData();

            fd.append("File", document.getElementById(senderObj).files[0])
            var filename = document.getElementById(senderObj).files[0].name;
          



            submitImage(evt, fd, "comic", txtUpdateField, imgUpdateField, filename);


        }
    </script>

}

APONCoreWebsite/Pages/Admin/AddSeriesCast.cshtml
@page
@model APONCoreWebsite.Pages.Admin.AddSeriesCastModel
@{
    ViewData["Title"] = "AddSeriesCast";
}

<h1>AddSeriesCast</h1>

APONCoreWebsite/Pages/Admin/EditEpisode.cshtml
@page "/Admin/EditEpisode/{EpisodeID}"
@model APONCoreWebsite.Pages.Admin.EditEpisodeModel
@{
    ViewData["Title"] = "Edit Episode";
}

<h1>EditEpisode</h1>

@if (Model.UserAuthLevel < 4)
{

    <div class="grid-row APONForm">
        <div class="col-1-of-1">
            <form method="post" asp-page-handler="Episode">
                <div class="form-group">
                    <label for="imageURL">Image URL</label>
                    <input type="text"
                           id="imageURL"
                           class="form-control"
                           asp-for="Episode.episode.EpImageURL"
                           name="imageURL"
                           oninput="UpdateEpisodeImage()" />
                </div>
                <div class="form-group">
                    <img id="imgEpisodeImage" class="edit-episode-image" src="@Model.Episode.episode.EpImageURL" />
                </div>
                <div class="form-group">
                    <label for="fileURL">File URL</label>
                    <input type="text"
                           id="fileURL"
                           class="form-control"
                           asp-for="Episode.episode.FileURL"
                           name="fileURL" />
                </div>
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                           id="EpTitle"
                           class="form-control"
                           asp-for="Episode.episode.Title"
                           name="EpTitle" />
                </div>
                <div class="form-group">
                    <label for="postDate">Post Date</label>
                    <input type="datetime-local"
                           id="showDate"
                           class="form-control"
                           asp-for="Episode.episode.ShowDate"
                           name="showDate" />
                </div>
                <div class="form-group">
                    <label for="postDate">Episode Length (time hh:mm:ss include 0's such as 01:03:05)</label>
                    <input type="text"
                           id="showTime"
                           class="form-control"
                           asp-for="Episode.episode.Time"
                           name="showTime" />
                </div>

                <div class="form-group">
                    <label for="description">Web Description</label>

                    <textarea id="tinyMCETextArea" name="tinyMCETextArea" asp-for="Episode.episode.WebDescription">

</textarea>
                </div>
                <div class="form-group mt-3">
                    <label for="webdescription">itunes Description. This cannot have HTML in it.</label>
                    <input type="text"
                           id="shortDescription"
                           class="form-control"
                           name="shortDescription" asp-for="Episode.episode.Description" />
                </div>
                <partial name="_tagConsole" model=@Model.TCM />

                <button class="btn btn-primary" type="submit">Save</button>
                <button class="btn btn-warning" type="button">
                    Cancel
                </button>




            </form>
        </div>
    </div>

}

@section Scripts
{

    <script type="text/javascript">


        $(document).ready(function () {
            CheckIfEditor(@Model.UserAuthLevel);


            var myTinyMCE = new tinymce.Editor('tinyMCETextArea', {
                selector: 'tinyMCETextArea',
                width: 900, height: 500,
                menubar: false,
                toolbar: 'code undo redo | bold italic underline strikethrough |  image media  link   | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print  | ltr rtl',
                toolbar_sticky: true,
                plugins: 'image link media code'
            }, tinymce.EditorManager);
            myTinyMCE.render();

            filterTagList();
            populateSelectedTagList();

            let status = "@Model.SaveStatus";

            if (status == "Saved") {
                alert("The Episode has been saved!");
            }
            if (status == "Forbidden") {
                alert("You can't edit episodes from this series.");
            }
            if (status == "Unauthorized") {
                alert("You do not have permission to edit episodes.");
            }
            if (status == "Error") {
                alert("There was an error saving.");
            }
        });

            function UpdateEpisodeImage() {
                document.getElementById("imgEpisodeImage").src = document.getElementById("imageURL").value;
            }
    </script>
}

APONCoreWebsite/Pages/Admin/TagHandler.cshtml
@page
@model APONCoreWebsite.Pages.Admin.TagHandlerModel
@{
    ViewData["Title"] = "TagHandler";
}

<h1>TagHandler</h1>

APONCoreWebsite/Pages/Admin/UserList.cshtml
@page "/Admin/UserList"
@model APONCoreWebsite.Pages.Admin.UserListModel
@{
    ViewData["Title"] = "UserList";
}


@{
    if (Model.UserAuthLevel < 3)
    {

        <table>
            <tr>
                <th>User ID</th>
                <th>User Name</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Last Login</th>
                <th>Image</th>
                <th>Creation Date</th>
                <th>Email</th>
                <th>Access Level</th>
            </tr>
            @{
                foreach (APONCoreLibrary.Models.User U in Model.Users)
                {
                    <tr>
                        <td>@U.UserID</td>
                        <td>@U.UserName</td>
                        <td>@U.FirstName</td>
                        <td>@U.LastName</td>
                        <td>@U.LastLogin.ToShortDateString()</td>
                        <td><img src="@U.ImageURL" style="width: 50px;" /></td>
                        <td>@U.CreationDate.ToShortDateString()</td>

                        <td>@U.Email</td>
                        <td>@U.AccessLevel</td>
                    </tr>
                }
            }

        </table>



    }

}

@section Scripts
{
    <script type="text/javascript">
    $(document).ready(function () {

        CheckIfAdmin(@Model.UserAuthLevel);
    });

    </script>

}