APONCoreWebsite/Pages/AboutUs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using APONCoreLibrary.ReturnModels;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages
{
    public class AboutUsModel : ViewModelBase
    {
        [BindProperty]
        public AboutUsPageInfo Info { get; set; }
        public AboutUsModel(IAuthService authService,  IMetaTagService imts,  IDataService ds) : base(authService, imts, ds)
        {
            

        }
        public async Task<IActionResult> OnGetAsync()
        {

            string Response = await DS.GetAsync("AboutUs/GetAboutUsPageInfo");
            Info = Newtonsoft.Json.JsonConvert.DeserializeObject<AboutUsPageInfo>(Response);

            IMTS.setParams("https://www.allportsopen.com/AboutUs", "article", "About Us", "The All Ports Open Network Crew", "https://media.allportsopen.org/Images/LogoSmWText.png");

            return Page();
        }
    }
}

APONCoreWebsite/Pages/AutoLogin.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using APONCoreLibrary.Models;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages
{
    public class AutoLoginModel : ViewModelBase
    {
        UserReturnToken URT { get; set; }



 
        public AutoLoginModel( IAuthService authService, IDataService ds, IMetaTagService imts) : base(authService, imts, ds)
        {
      
        }
        public JsonResult OnGet()
        {
            JsonResult js = new JsonResult("This is a value");
            return js;
        }

        public void OnPostLogout()
        {
            string s = myAuthService.Logout();
            myAuthService.Logout();
            Response.Redirect("/");
        }

        public IActionResult OnPostURT([FromBody] object JwtValue)
        {
            if (JwtValue != null)
            {
                string j = JwtValue.ToString();
              
                URT = new UserReturnToken(j);
            
                myAuthService.SaveUserSessionData(URT);
               
            }
            else
            {
                myAuthService.Logout();
            }
            return Page();
        }
    }


}

APONCoreWebsite/Pages/CastList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using APONCoreLibrary.Models;
using APONCoreLibrary.Models.ReturnModels;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages
{
    public class CastListModel : ViewModelBase

    {
        [BindProperty(SupportsGet =true)]
        public int SeriesID { get; set; }

        public APONCoreLibrary.Models.Series series { get; set; }

        public List<SeriesCastType> Types { get; set; }

        public CastWithSocialMedia CastList { get; set; }

        public CastListModel(IDataService ds, IAuthService authService,  IMetaTagService imts) : base(authService, imts, ds)
        {


        }
        public async Task<IActionResult> OnGetAsync()
        {
            string Response = await DS.GetAsync("cast/GetCastForSeries_TypeSafe/" + SeriesID);

            CastList = Newtonsoft.Json.JsonConvert.DeserializeObject<CastWithSocialMedia>(Response);


            string SeriesResponse = await DS.GetAsync("series/" + SeriesID);
            series = Newtonsoft.Json.JsonConvert.DeserializeObject<APONCoreLibrary.Models.Series>(SeriesResponse);


            IMTS.setParams("https://www.allportsopen.com/cast/" + SeriesID, "article", "Cast for " + series.Name, "Cast for the " + series.Name + " podcast", series.ImageURL);


            return Page();
        }
    }
}

APONCoreWebsite/Pages/ComicStrips.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using APONCoreLibrary.Models;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages
{
    public class ComicStripsModel : ViewModelBase
    {
       public List<ComicStrip> Strips { get; set; }
        public ComicStripsModel(IAuthService authService, IDataService ds, IMetaTagService imts) : base(authService, imts, ds)
        {

        }

        public async Task<IActionResult> OnGetAsync()
        {
            string ComicListResponse = await DS.GetAsync("comic/GetAllComics");
            Strips = Newtonsoft.Json.JsonConvert.DeserializeObject<List<ComicStrip>>(ComicListResponse);
            return Page();
        }
    }
}

APONCoreWebsite/Pages/EditComment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using APONCoreLibrary.Models;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using System.Net.Http;

namespace APONCoreWebsite.Pages
{
    public class EditCommentModel : ViewModelBase
    {
        [BindProperty(SupportsGet = true)]
        public int ForumPostID { get; set; }
        public ForumPost FP { get; set; }
        public string ReturnURL { get; set; }

        public string Mode { get; set; }
        public EditCommentModel(IDataService ds, IAuthService authService, IMetaTagService imts) : base(authService, imts, ds)
        {

        }

        public async Task<IActionResult> OnGetAsync()
        {
            Mode = "Edit";
            ReturnURL = Request.Headers["Referer"].ToString();
            string result = await DS.GetAsync("Forum/GetForumPost/" + ForumPostID);
            FP = Newtonsoft.Json.JsonConvert.DeserializeObject<ForumPost>(result);

            return Page();
        }

        public async Task<IActionResult> OnPostCommentAsync()
        {
            string result = await DS.GetAsync("Forum/GetForumPost/" + ForumPostID);
            FP = Newtonsoft.Json.JsonConvert.DeserializeObject<ForumPost>(result);

            FP.Text = Request.Form["tinyMCETextArea"];

            HttpResponseMessage Response = await DS.PutAsync(FP, "Forum/UpdateForumPost");

            ReturnURL = Request.Form["returnURL"];
            Mode = "Saved";
            return Page();
        }
    }
}

APONCoreWebsite/Pages/Episode.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using APONCoreLibrary.Models;
using APONCoreLibrary.Models.RequestModels;
using APONCoreLibrary.ReturnModels;
using APONCoreWebsite.Models;
using APONCoreWebsite.Pages.Shared;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;

namespace APONCoreWebsite.Pages.Series
{
    [BindProperties]
    public class EpisodeModel : ViewModelBase
    {
        [BindProperty(SupportsGet = true)]
        public int EpisodeID { get; set; }
        public EpisodePageData EpisodeData { get; set; }

        public Episode Episode { get; set; }


        public List<Tag> Tags { get; set; }

        public string SeriesName { get; set; }

        public UserBriefWithBadges Author { get; set; }

        public string FileURL { get; set; }

        public ISeriesService SS { get; set; }

        public int CurrentUserID { get; set; }

        [BindProperty]
        public APONCoreLibrary.Models.Series epSeries { get; set; }

        public Shared._ForumViewModel fvm { get; set; }
        public EpisodeModel(IDataService ds, IAuthService authService, IMetaTagService imts, ISeriesService ss) : base(authService, imts, ds)
        {
            SS = ss;

        }

        public async Task<IActionResult> OnGetAsync()
        {
            if (EpisodeID == 0)
            {
                return Page();
            }
            string result = "";
            try
            {
                result = await DS.GetAsync("Episodes/GetEpisodePageData/" + EpisodeID);

            }
            catch (Exception ex)
            {
                if (ex.Message.Contains("404"))
                {
                    Response.Redirect("/");
                    Episode = new Episode();
                    Episode.Title = "No Episode Found";
                    Episode.EpisodeID = -1;
                    return Page();
                }
            }
            EpisodeData = Newtonsoft.Json.JsonConvert.DeserializeObject<EpisodePageData>(result);

            if (EpisodeData.EpWithTag.episode.Local)
            {
                FileURL = "https://media.allportsopen.org/Podcasts/" + EpisodeData.Series.Folder + EpisodeData.EpWithTag.episode.FileURL;
            }
            else
            {
                FileURL = EpisodeData.EpWithTag.episode.FileURL;
            }

            //
            IMTS.setParams("https://www.allportsopen.com/Series/Episode/" + EpisodeData.EpWithTag.episode.EpisodeID, "article", EpisodeData.Series.Name + " Podcast " + EpisodeData.EpWithTag.episode.Title, EpisodeData.EpWithTag.episode.Description, EpisodeData.EpWithTag.episode.EpImageURL);

            Episode = EpisodeData.EpWithTag.episode;
            Tags = EpisodeData.EpWithTag.tags;
            SeriesName = EpisodeData.Series.Name;
            Author = EpisodeData.Author;

            //TODO: add current user ID to forum post page and compare with forum post info

            fvm = new Shared._ForumViewModel();
            fvm.Forum = EpisodeData.Forum;
            fvm.ForumLUI = EpisodeData.ForumLUI;
            fvm.Posts = new List<_Forum__PostModel>();
            foreach (ForumPostInfo fpi in EpisodeData.Posts)
            {
                fpi.CurrentUserID = myAuthService.getUserID();
                _Forum__PostModel f = new _Forum__PostModel(fpi, myAuthService.getUserID());
                fvm.Posts.Add(f);

            }
            CurrentUserID = myAuthService.getUserID();
            fvm.CurrentUserID = myAuthService.getUserID();
            fvm.ShowTop = false;

            metaData md = new metaData();
            md.description = Episode.Description;
            md.image = Episode.EpImageURL;
            md.title = Episode.Title;
            md.type = "article";
            md.URL = "https://www.allportsopen.com/series/Episode/" + Episode.EpisodeID;

            epSeries = await SS.GetSeriesByID(Episode.SeriesID);
            return Page();
        }
    }
}

APONCoreWebsite/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace APONCoreWebsite.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

APONCoreWebsite/Pages/Feature.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using APONCoreLibrary.Models;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages
{
    public class FeatureModel : ViewModelBase
    {
        [BindProperty(SupportsGet = true)]
        public int FeatureID { get; set; }

     

        public NewsWithTags Feature { get; set; }

        public int CurrentUserID {get; set;}

     

        public FeatureModel(IAuthService authService, IMetaTagService imts, IDataService ds) : base(authService, imts, ds)
        {
           
        }
    
        public async Task<IActionResult> OnGetAsync()
        {
            if (FeatureID == 0)
            {
                return Page();
            }
            CurrentUserID = myAuthService.getUser().UserID;
            string response = await DS.GetAsync("News/GetNewsItemWTags/" + FeatureID);
            Feature = Newtonsoft.Json.JsonConvert.DeserializeObject<NewsWithTags>(response);
           // Feature.News.LongText = Feature.News.LongText.Replace("<img", "<img style='width:100%'");

            IMTS.setParams("https://www.allportsopen.com/Feature/" + Feature.News.NewsID, "article", Feature.News.Headline, Feature.News.Text, Feature.News.ImageURL);

            return Page();
        }
    }
}

APONCoreWebsite/Pages/Features.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Helpers;
using APONCoreLibrary.Models;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages
{
    public class FeaturesModel : ViewModelBase
    {
      

        [BindProperty]
       public List<News> News { get; set; }

        
        public FeaturesModel(IAuthService authService, IMetaTagService imts, IDataService ds): base(authService, imts, ds)
        {
           

        }

        public async Task<IActionResult> OnGetAsync()
        {
            string response = await DS.GetAsync("news/GetNewsList");
            News = Newtonsoft.Json.JsonConvert.DeserializeObject<List<News>>(response);




            return Page();


        }
    }
}

APONCoreWebsite/Pages/ImageHandler.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using APONCoreWebsite.Pages.ViewModels;
using APONCoreWebsite.Services;
using System.Net.Http;
using System.Web.Helpers;

namespace APONCoreWebsite.Pages
{
    public class ImageHandlerModel : ViewModelBase
    {
     
        public ImageHandlerModel(IAuthService authService, IMetaTagService imts, IDataService ds) : base(authService, imts, ds)
        {
          
        }

        [BindProperty, Display(Name = "File")]
        public IFormFile UploadedFile { get; set; }
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostNewsImage()
        {
            IFormFile FileData = Request.Form.Files[0];
            string type = Request.Form["imageType"];
       
            string Message = "";
            string path = "";
       
            if (type == "episode")
            {
                path = "Episodes/UploadEpisodeImage";
            }
            else if (type == "news")
            {
                path = "News/UploadNewsImage";
            }
            else if (type == "comic")
            {
                path = "Comic/UploadComicImage";
            }

            HttpResponseMessage response = await DS.PostImageAsync(FileData, path);

            if (response.StatusCode == System.Net.HttpStatusCode.Created)
            {
                Message = "";
            }
            else
            {
                Message = "Error Uploading File: " + response.Content.ToString();
            }

            JsonResult result = new JsonResult(Message);

            return result;
        }

        public async Task<IActionResult> OnPostEpImage()
        {
            IFormFile FileData = Request.Form.Files[0];
            string Message = "";

            HttpResponseMessage response = await DS.PostImageAsync(FileData, "Episode/UploadEpisodeImage");

            if (response.StatusCode == System.Net.HttpStatusCode.Created)
            {
                Message = "";
            }
            else
            {
                Message = "Error Uploading File: " + response.Content.ToString();
            }

            JsonResult result = new JsonResult(Message);

            return result;
        }
    }
}

APONCoreWebsite/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace APONCoreWebsite.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

APONCoreWebsite/Pages/_CastGroup.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace APONCoreWebsite.Pages
{
    public class _CastGroupModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

APONCoreWebsite/Pages/AboutUs.cshtml
@page
@model APONCoreWebsite.Pages.AboutUsModel
@{
    ViewData["Title"] = "AboutUs";
}

<div class="row APONText">
    <div class="col-12">
        <span class="pageHeader">About Us</span>
    </div>
</div>
<div *ngIf="aboutUsData" class="APONText block">
    <div class="AboutUsHeader">
        <img class="AboutUsHeader__image u-margin-bottom-4"
             src="@Model.Info.AboutUsInfo.ImageURL" />
        <div class="AboutUsHeader__text">
            <p class="paragraph">@Html.Raw(Model.Info.AboutUsInfo.Text)</p>
        </div>
    </div>
</div>
<hr />
<div *ngIf="crewList">

    @{
        for (int i = 0; i < Model.Info.CrewMembers.Count; i++)
        {
            if (i % 4 == 0)
            {
                <div class="grid-row APONText">
                    @if (Model.Info.CrewMembers.Count > i)
                    {<div class="col-1-of-4">
                            <partial name="_CrewMemberCard" model=@Model.Info.CrewMembers[i] />
                        </div>
                    }
                    @if (Model.Info.CrewMembers.Count > i + 1)
                    {<div class="col-1-of-4">
                            <partial name="_CrewMemberCard" model=@Model.Info.CrewMembers[i + 1] />
                        </div>
                    }
                    @if (Model.Info.CrewMembers.Count > i + 2)
                    {<div class="col-1-of-4">
                            <partial name="_CrewMemberCard" model=@Model.Info.CrewMembers[i + 2] />
                        </div>
                    }
                    @if (Model.Info.CrewMembers.Count > i + 3)
                    {<div class="col-1-of-4">
                            <partial name="_CrewMemberCard" model=@Model.Info.CrewMembers[i + 3] />
                        </div>
                    }
                </div>

            }
        }
    }

</div>

APONCoreWebsite/Pages/AutoLogin.cshtml
@page
@model APONCoreWebsite.Pages.AutoLoginModel
@{
    ViewData["Title"] = "AutoLogin";
}

<h1>AutoLogin</h1>

APONCoreWebsite/Pages/CastList.cshtml
@page "{SeriesID}"
@model APONCoreWebsite.Pages.CastListModel
@using APONCoreLibrary.Models;
@using APONCoreLibrary.ReturnModels;
@{
    ViewData["Title"] = "Cast";
}



<div style="margin-top: 2rem;">
    <h2>
        <span class="pageHeader">Cast List for @Model.series.Name </span>
    </h2>

</div>

<div>
    @{
        List<SeriesCastInfo> CTCastInfo = new List<SeriesCastInfo>();

        for (int j = 0; j < Model.CastList.castTypes.Count; j++)
        {
            <div class="grid-row mt-5">
                <span class="APONSubHeader">
                    @Model.CastList.castTypes[j].Name
                </span>

                @{CTCastInfo = Model.CastList.cast.Where(x => x.SeriesCastTypeID == Model.CastList.castTypes[j].SeriesCastTypeID).ToList<SeriesCastInfo>();
                    <section class="cast-grid APONText mt-5 mb-5">

                        @for (int i = 0; i < CTCastInfo.Count; i++)
                        {
                            if (i % 4 == 0)
                            {
                                <div class="grid-row">
                                    @if (CTCastInfo.Count > i)
                                    {
                                        <div class="col-1-of-4">
                                            <partial name="_CastCard" model=@CTCastInfo[i] />

                                        </div>
                                    }
                                    @if (CTCastInfo.Count > i + 1)
                                    {
                                        <div *ngIf="cast.length > i + 1" class="col-1-of-4">
                                            <partial name="_CastCard" model=@CTCastInfo[i + 1] />

                                        </div>
                                    }
                                    @if (CTCastInfo.Count > i + 2)
                                    {
                                        <div *ngIf="cast.length > i + 2" class="col-1-of-4">
                                            <partial name="_CastCard" model=@CTCastInfo[i + 2] />
                                        </div>
                                    }
                                    @if (CTCastInfo.Count > i + 3)
                                    {
                                        <div *ngIf="cast.length > i + 3" class="col-1-of-4">
                                            <partial name="_CastCard" model=@CTCastInfo[i + 3] />
                                        </div>
                                    }
                                </div>
                            }
                        }
                    </section>

                }



                <hr />
            </div>
        }
    }

</div>

APONCoreWebsite/Pages/ComicStrips.cshtml
@page "/ComicStrips"
@model APONCoreWebsite.Pages.ComicStripsModel
@using APONCoreLibrary.Models; 
@{
    foreach(ComicStrip CS in Model.Strips)
    {
        <div>@CS.Name</div>
        <div><img src="@CS.ImageURL" /></div>
    }
}

APONCoreWebsite/Pages/EditComment.cshtml
@page "/EditComment/{ForumPostID}"
@model APONCoreWebsite.Pages.EditCommentModel
@{
    <form method="post" id="frmMain" asp-page-handler="Comment" style="display:none">
        <textarea id="tinyMCETextArea" name="tinyMCETextArea" asp-for="FP.Text"></textarea>
        <button type="submit">Save</button>
        <button type="button" onclick="window.location.href='@Model.ReturnURL'">Cancel</button>
        <input type="hidden" id="returnURL" name="returnURL" asp-for="ReturnURL" />
    </form>
 
}

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            if ("@Model.Mode" == "Edit") {
                var myTinyMCE = new tinymce.Editor('tinyMCETextArea', {
                    selector: 'tinyMCETextArea',
                    width: 1000, height: 500,
                    menubar: false,
                    toolbar: 'code undo redo | bold italic underline strikethrough |  image media  link   | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | pagebreak | charmap emoticons | fullscreen  preview save print  | ltr rtl',
                    toolbar_sticky: true,
                    plugins: 'image link media code'
                }, tinymce.EditorManager);

                myTinyMCE.render();
                document.getElementById("frmMain").style.display = "block";
            }
            else {
                alert("Comment saved!");
                window.location.href = '@Model.ReturnURL';
            }

        }
        );
    </script>
}

APONCoreWebsite/Pages/ImageHandler.cshtml
@page
@model APONCoreWebsite.Pages.ImageHandlerModel
@{
    ViewData["Title"] = "ImageHandler";
}

<h1>ImageHandler</h1>

APONCoreWebsite/Pages/Tag.cshtml
@page "/Tag/{TagID}"
@model APONCoreWebsite.Pages.TagModel
@{
    ViewData["Title"] = "Tag";
}

<h1>Tag: @Model.TB.Name</h1>
<br />
<br />

<div class="grid-row">
    <div class="col-1-of-2">
        <h3>Podcast Episodes</h3>
        <br />
        <br />
        @for (int i = 0; i < Model.TB.Eps.Count; i++)
        {
            <div class="grid-row">
                <a href="../../series/episode/@Model.TB.Eps[i].EpisodeID">
                    <div class="col-1-of-3">
                        <img src="@Model.TB.Eps[i].EpImageURL" style="width:10vw" />
                    </div>
                    <div class="col-2-of-3">
                        <label> @Model.TB.Eps[i].Title</label>
                    </div>

                </a>
            </div>
            <br />
        }
    </div>

    <div class="col-1-of-2">
        <h3>Features</h3>
        @for (int j = 0; j < Model.TB.News.Count; j++)
        {
            <div class="grid-row">
                <a href="../../feature/@Model.TB.News[j].NewsID">
                    <div class="col-1-of-3">
                        <img src="@Model.TB.News[j].ImageURL" style="width:10vw" />
                    </div>
                    <div class="col-2-of-3">
                        <label> @Model.TB.News[j].Headline</label>
                    </div>

                </a>
            </div>
            <br />

            <label></label>
            <br />
        }
    </div>
</div>

APONCoreWebsite/Pages/Test.cshtml
@page
@model APONCoreWebsite.Pages.TestModel
@{

    <partial name="_Forum" model="Model.FWP" />
}

APONCoreWebsite/Pages/User.cshtml
@page
@model APONCoreWebsite.Pages.Shared.UserModel
@{
    ViewData["Title"] = "User";
}

<div class="APONText">
    test
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <h2 class="pageHeader">@Model.UBWB.User.UserName</h2>
            @if (@Model.isProfileUser)
            {
                <form id="logoutForm" name="logoutForm" asp-page="AutoLogin"  asp-page-handler="Logout">
                    <button type="button" class="APONbtn APONbtnBlue"
                            onclick="logout()">
                        Logout
                    </button>
                </form>

            }
        </div>
    </div>
    <div class="grid-row">
        <div class="col-2-of-4">
            <div>
                <div>
                    <img src=@Model.UBWB.User.ImageURL class="profileImage" />
                    @if (@Model.isProfileUser)
                    {
                        <div *ngIf="ownerProfile">
                            <input type="text"
                                   name="txtImgURL"
                                   asp-for="UBWB.User.ImageURL" />
                            <button class="APONbtn APONbtnOrange" click="SaveUserImage">
                                Save Profile Image
                            </button>
                        </div>
                    }
                    <hr />
                    <app-user-badge-grid *ngIf="badgesPresent()"
                                         [badges]="profileUserData.badges"></app-user-badge-grid>
                </div>
            </div>
        </div>
        <div class="col-1-of-4">
            <form #PWForm="ngForm"
                  *ngIf="ownerProfile"
                  (ngSubmit)="onSubmitPW(PWForm)">
                <h3>Reset your password</h3>
                <div class="small-grid-row">
                    <div class="col-1-of-2">
                        <label for="OldPW">Old Password</label>
                    </div>
                    <div class="col-1-of-2">
                        <input type="text" id="OldPW" ngModel name="OldPW" />
                    </div>
                </div>
                <div class="small-grid-row">
                    <div class="col-1-of-2">
                        <label for="OldPW">New Password</label>
                    </div>
                    <div class="col-1-of-2">
                        <input type="text" id="NewPW" ngModel name="NewPW" />
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary"
                            type="submit"
                            [disabled]="!PWForm.valid">
                        Submit
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    <script type="text/javascript">
        function SaveUserImage() {

        }

        function logout() {
            
            var myStorage = window.localStorage;
            myStorage.removeItem("userJWT");
            document.getElementById("logoutForm").submit();
            logoutRefresh();
        }


    </script>

}